name: Sync upstream repository
on:
  schedule:
    - cron:  '0 0 * * *'  # 每天凌晨同步一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/yonggekkk/Cloudflare-vless-trojan.git || true
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories
          git push
